export const SET_SHARE_MODAL = "SET_SHARE_MODAL";
export const SET_SELECT_CONTACTS_MODAL = "SET_SELECT_CONTACTS_MODAL";
export const SET_INVITED_CONTACTS = "SET_INVITED_CONTACTS";
export const UPDATE_CONTACTS_ACCESS_LEVEL = "UPDATE_CONTACTS_ACCESS_LEVEL";
